# Generated by Django 2.2.14 on 2023-10-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футеры'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
